version: 2
jobs:
  venv:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - run:
          command: |
            echo "hi"
workflows:
  version: 2
  build_and_test:
    jobs:
      - venv
